global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@neoc-ai-assistant.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
  routes:
  - match:
      severity: critical
    receiver: 'email'
  - match:
      severity: warning
    receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'admin@neoc-ai-assistant.com'
    send_resolved: true

# For Slack notifications (uncomment and configure)
# - name: 'slack'
#   slack_configs:
#   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
#     channel: '#alerts'
#     send_resolved: true